import Layout from "@/components/layout";
import { API_KEY, BASE_PATH, BASE_URL, YT } from "@/lib/constant";
import Head from "next/head";
import { useRouter } from "next/router";
import Script from "next/script";
import { useEffect, useState } from "react";

function MovieDetail({trailer}) {
  const router = useRouter();
  const [m, setMovie] = useState(JSON.parse(router.query.movie));
  const [key, setKey] = useState("")
  useEffect(() => {
    
    setKey(trailer[trailer.length - 1].key)
    
  }, [])
  return (
    <Layout>
     <Head>
        <title>detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
     </Head>
     <div className="container d-flex p-2">
            
            <section className="p-2">
              <img src={BASE_PATH + m.poster_path} alt="thumnail" className="rounded"/>
            </section>
            <section className="m-2">
              <h1>
                {
                  m.title
                }
              </h1>
              <p>Overview</p>
              <p>
                {
                  m.overview
                }
              </p>
              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#playTrialer">
                  Watch Video
              </button>
            </section>

          <div class="modal fade" id="playTrialer" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-xl modal-dialog-centered">
              <div class="modal-content">
                
              <iframe height="573" src={YT + key} title="Chan Samai  មិនស្រលាញ់អូនមិនបាន   Lyric and Chords" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
        
              </div>
            </div>
          </div>

     </div>
    </Layout>
  );
}

export async function getServerSideProps({params}) {
    console.log(`${BASE_URL}movie/${params.id}/videos?api_key=${API_KEY}`)
    const res = await fetch(`${BASE_URL}movie/${params.id}/videos?api_key=${API_KEY}`)
    const resp = await res.json()
    
    return {
      props: {
        trailer: resp.results
      }, // will be passed to the page component as props
    }
  }
  export default MovieDetail;