import Layout from "@/components/layout";
import Head from "next/head";
import { useEffect, useState } from "react";
import axios from 'axios'
import DataTable from "react-data-table-component";

function Boss(){
    const [products, setProducts] = useState([])
    const [filterProducts, setFilterProducts] = useState([])
    const [search, setSearch] = useState('')

    const fetchProducts = async () => {
        const response = await axios.get("https://api.escuelajs.co/api/v1/products")
        setProducts(response.data)
        setFilterProducts(response.data)
    }

    const columns = [
        {
          name: "Product Name",
          selector: row => row.title,
          sortable: true
        },
        {
          name: "Price",
          selector: row => `${row.price} $`,
          sortable: true
        },
        {
          name: "Category",
          selector: row => row.category.name,
          sortable: true
        },
        {
          name: "Photos",
          selector: (row) => <img width={80} height={80} src={row.images[0]} />,
          sortable: true
        },
        {
          name: "Action",
          selector: row => <button className='btn btn-primary' onClick={() => alert(row.title)}>Edit</button>
        }
      ]

      useEffect(() => {
        fetchProducts()
      }, [])

      useEffect(() => {
        const result = products.filter(product => {
            return product.title.toLowerCase().match(search.toLowerCase())
        })
        setFilterProducts(result)
      }, [search])

    return (
        <Layout>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="container">
                <h1>Product Collection - Table</h1>
                <DataTable 
                    columns={columns} 
                    data={filterProducts}
                    pagination
                    subHeader
                    subHeaderComponent={
                        <input type="text" 
                        placeholder='search here' 
                        className='form-control'
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        />
                    }
                />
            </div>
        </Layout>
    )
}
export default Boss;